=== 3openmobilealliance/trial/DDF.XSD
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DDFList">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Item">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ObjectID" type="xs:unsignedShort" />
              <xs:element name="URN" type="xs:string" />
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Description" type="xs:string" />
              <xs:element name="Owner" type="xs:string" />
              <xs:element name="Source" type="xs:unsignedByte" />
              <xs:element name="Ver" type="xs:string" />
              <xs:element name="DDF" type="xs:string" />
              <xs:element name="Vorto" type="xs:string" />
              <xs:element name="DDFLink" type="xs:string" />
              <xs:element name="TS" type="xs:string" />
              <xs:element name="TSLink" type="xs:string" />
              <xs:element minOccurs="0" name="LicenseType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 3openmobilealliance/trial/DDF.xml
<?xml version="1.0" encoding="UTF-8" ?>
<DDFList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/DDF.xsd">
    <Item>
        <!-- Integer -->
        <!-- ObjectID -->
        <ObjectID>0</ObjectID>
        <!-- URN of the object -->
        <URN>urn:oma:lwm2m:oma:0</URN>
        <!-- Name of the object -->
        <Name>LWM2M Security</Name>
        <!-- Description of the Object -->
        <Description>This LwM2M Object provides the keying material of a LwM2M Client appropriate to access a specified LwM2M Server. One Object Instance SHOULD address a LwM2M Bootstrap-Server.
These LwM2M Object Resources MUST only be changed by a LwM2M Bootstrap-Server or Bootstrap from Smartcard and MUST NOT be accessible by any other LwM2M Server.</Description>
        <!-- Name of the organization that has registered the object -->
        <Owner>Test WG</Owner>
        <!-- Type of Object: 0 = defined by OMA, 1 = defined by external Standards Development Organizations, 2 = private or individual -->
        <Source>0</Source>
        <!-- Ver of the object, not visible, not used -->
        <Ver>1.0</Ver>
        <!-- URL to the xml file describing the object -->
        <DDF>LWM2M_Security-v1_0.xml</DDF>
        <!-- Link that opens the object in the LwM2M Editor Tool -->
        <LWM2M>LWM2M_Security-v1_0.xml</LWM2M>
        <!-- Link that opens the Object in the Vorto environment -->
        <Vorto>http://vorto.eclipse.org/resolve/lwm2m/Object/ObjectID/0</Vorto>
        <!-- 0 => if link to object should not be visible, 1 => if object should be visible (default) -->
        <DDFLink>1</DDFLink>
        <!-- URL to the TS of the object, not visible, not used -->
        <TS>http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf</TS>
        <!-- 0 => if link to TS should not be visible, 1 => if link to TS should be visible (default) -->
        <TSLink>1</TSLink>
    </Item>
    
     <Item>
        <ObjectID>1</ObjectID>
        <URN>urn:oma:lwm2m:oma:1</URN>
        <Name>LwM2M Server</Name>
        <Description>This LwM2M Objects provides the data related to a LwM2M Server. A Bootstrap-Server has no such an Object Instance associated to it.</Description>
        <Owner>OMA</Owner>
        <Source>0</Source>
        <Ver>1.0</Ver>
        <DDF>LWM2M_Server-v1_0.xml</DDF>
        <LWM2M>LWM2M_Server-v1_0.xml</LWM2M>
        <Vorto>http://vorto.eclipse.org/resolve/lwm2m/Object/ObjectID/1</Vorto>
        <DDFLink>1</DDFLink>
        <TS>http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf</TS>
        <TSLink>1</TSLink>
    </Item>   
    
    <Item>
        <ObjectID>2</ObjectID>
        <URN>urn:oma:lwm2m:oma:2</URN>
        <Name>LwM2M Access Control</Name>
        <Description>It is used to check whether the LWM2M Server has access right for performing a operation.</Description>
        <Owner>OMA</Owner>
        <Source>0</Source>
        <Ver>1.0</Ver>
        <DDF>LWM2M_Access_Control-v1_0_2.xml</DDF>
        <LWM2M>LWM2M_Access_Control-v1_0_2.xml</LWM2M>
        <Vorto>http://vorto.eclipse.org/resolve/lwm2m/Object/ObjectID/2</Vorto>
        <DDFLink>1</DDFLink>
        <TS>http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf</TS>
        <TSLink>1</TSLink>
    </Item>
    
    <Item>
        <ObjectID>2048</ObjectID>
        <URN>urn:oma:lwm2m:ext:2048</URN>
        <Name>CmdhPolicy</Name>
        <Description>This Object provides links to a set of rules associated with a specific CSE that governs the behavior 
            of that CSE regarding rejecting, buffering and sending request or response messages via the Mcc reference point.</Description>
        <Owner>oneM2M</Owner>
        <Source>1</Source>
        <Ver>1.0</Ver>
        <DDF>2048.xml</DDF>
        <LWM2M>2048.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS>http://www.onem2m.org/images/files/deliverables/TS-0005-Management_Enablement_(OMA)-V1_0_1.pdf</TS>
        <TSLink>1</TSLink>
    </Item>

    <Item>
        <ObjectID>2049</ObjectID>
        <URN>urn:oma:lwm2m:ext:2049</URN>
        <Name>ActiveCmdhPolicy</Name>
        <Description>This Object provides a link to the currently active set of CMDH policies</Description>
        <Owner>oneM2M</Owner>
        <Source>1</Source>
        <Ver>1.0</Ver>
        <DDF>2049.xml</DDF>
        <LWM2M>2049.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS>http://www.onem2m.org/images/files/deliverables/TS-0005-Management_Enablement_(OMA)-V1_0_1.pdf</TS>
        <TSLink>1</TSLink>
    </Item>

    <Item>
        <ObjectID>2050</ObjectID>
        <URN>urn:oma:lwm2m:ext:2050</URN>
        <Name>CmdhDefaults</Name>
        <Description>Defines which CMDH related parameters will be used by default.</Description>
        <Owner>oneM2M</Owner>
        <Source>1</Source>
        <Ver>1.0</Ver>
        <DDF>2050.xml</DDF>
        <LWM2M>2050.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS>http://www.onem2m.org/images/files/deliverables/TS-0005-Management_Enablement_(OMA)-V1_0_1.pdf</TS>
        <TSLink>1</TSLink>
    </Item>

    <Item>
        <ObjectID>10241</ObjectID>
        <URN>urn:oma:lwm2m:x:10241</URN>
        <Name>HostDeviceInfo</Name>
        <Description>This LWM2M Object provides a range of host device related information which can be queried by the LWM2M Server. The host device is any integrated device with an embedded cellular radio module.</Description>
        <Owner>AT&amp;T</Owner>
        <Source>2</Source>
        <Ver>1.0</Ver>
        <DDF>rel1/10241.xml</DDF>
        <LWM2M>rel1/10241.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS></TS>
        <TSLink>0</TSLink>
    </Item>
    
    <Item>
        <ObjectID>10241</ObjectID>
        <URN>urn:oma:lwm2m:x:10241:1.1</URN>
        <Name>HostDeviceInfo</Name>
        <Description>This LWM2M Object provides a range of host device related information which can be queried by the LWM2M Server. The host device is any integrated device with an embedded cellular radio module.</Description>
        <Owner>AT&amp;T</Owner>
        <Source>2</Source>
        <Ver>1.1</Ver>
        <DDF>rel2/10241.xml</DDF>
        <LWM2M>rel2/10241.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS></TS>
        <TSLink>0</TSLink>
    </Item> 
    
    <Item>
        <ObjectID>10241</ObjectID>
        <URN>urn:oma:lwm2m:x:10241:1.2</URN>
        <Name>HostDeviceInfo</Name>
        <Description>New revision 10241 v1.2</Description>
        <Owner>AT&amp;T</Owner>
        <Source>2</Source>
        <Ver>1.2</Ver>
        <DDF>10241.xml</DDF>
        <LWM2M>10241.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS></TS>
        <TSLink>0</TSLink>
    </Item>     
    
    <Item>
        <ObjectID>10242</ObjectID>
        <URN>urn:oma:lwm2m:x:10242</URN>
        <Name>3-Phase Power Meter</Name>
        <Description>This Object provides the information to represent a generic 3-Phase Power Meter</Description>
        <Owner>Odins</Owner>
        <Source>2</Source>
        <Ver>1.0</Ver>
        <DDF>10242.xml</DDF>
        <LWM2M>10242.xml</LWM2M>
        <Vorto></Vorto>
        <DDFLink>1</DDFLink>
        <TS></TS>
        <TSLink>0</TSLink>
    </Item>     
</DDFList>
